- name: Setup PostgreSQL Primary and Replica Using Docker
  hosts: all
  become: yes

  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes

    - name: Install Docker & Docker-Compose
      apt:
        name: 
          - docker.io
          - docker-compose
        state: present

    - name: Create required directories
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - /opt/postgres-replication
        - /opt/postgres-replication/primary
        - /opt/postgres-replication/replica

    - name: Create Docker Compose file
      copy:
        dest: /opt/postgres-replication/docker-compose.yml
        content: |
          version: '3.8'

          services:
            primary:
              image: postgres:13
              container_name: postgres_primary
              restart: always
              environment:
                POSTGRES_USER: admin
                POSTGRES_PASSWORD: admin123
                POSTGRES_DB: mydb
              ports:
                - "5432:5432"
              volumes:
                - primary_data:/var/lib/postgresql/data
                - ./primary/postgresql.conf:/etc/postgresql/postgresql.conf
                - ./primary/pg_hba.conf:/etc/postgresql/pg_hba.conf
              command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf", "-c", "hba_file=/etc/postgresql/pg_hba.conf"]

            replica:
              image: postgres:13
              container_name: postgres_replica
              restart: always
              environment:
                POSTGRES_USER: admin
                POSTGRES_PASSWORD: admin123
              depends_on:
                - primary
              ports:
                - "5433:5432"
              volumes:
                - replica_data:/var/lib/postgresql/data
                - ./replica/postgresql.conf:/etc/postgresql/postgresql.conf
                - ./replica/pg_hba.conf:/etc/postgresql/pg_hba.conf
              command: ["/bin/bash", "-c", "
                until pg_isready -h primary -p 5432; do sleep 2; done &&
                PGPASSWORD=admin123 pg_basebackup -h primary -D /var/lib/postgresql/data -U admin -Fp -Xs -R -C -S replica_slot &&
                postgres -c config_file=/etc/postgresql/postgresql.conf
              "]

          volumes:
            primary_data:
            replica_data:
    
    - name: Create PostgreSQL primary config
      copy:
        dest: /opt/postgres-replication/primary/postgresql.conf
        content: |
          listen_addresses = '*'
          wal_level = replica
          max_wal_senders = 3
          wal_keep_size = 64MB
          hot_standby = on
          archive_mode = on
          archive_command = 'cp %p /var/lib/postgresql/archive/%f'

    - name: Create PostgreSQL primary authentication file
      copy:
        dest: /opt/postgres-replication/primary/pg_hba.conf
        content: |
          local   all             all                                     trust
          host    all             all             0.0.0.0/0               md5
          host    replication     admin           0.0.0.0/0               md5
          host    replication     admin           172.18.0.3/32           md5  # Allow replica IP


    - name: Create PostgreSQL replica config
      copy:
        dest: /opt/postgres-replication/replica/postgresql.conf
        content: |
          port = 5433
          hot_standby = on
          primary_conninfo = 'host=primary port=5432 user=admin password=admin123'
          primary_slot_name = 'replica_slot'

    - name: Create PostgreSQL replica authentication file
      copy:
        dest: /opt/postgres-replication/replica/pg_hba.conf
        content: |
          local   all             all                                     trust
          host    all             all             0.0.0.0/0               md5
          host    replication     admin           0.0.0.0/0               md5

    - name: Start Docker Services
      shell: |
        cd /opt/postgres-replication
        docker-compose up -d


